import React,{useState} from 'react';
import {Lock,ShieldCheck,CheckCircle2,XCircle,Database,ArrowRight} from 'lucide-react';
import {ConvergedProposal,TwinMindCase,GovernorVaultRecord,ChekAuditStage,InvariantEvaluation,ChekVerificationRecord} from '../types/architecture';
import {GovernorPolicyEngine} from '../engine/governorEngine';
import {ChekVerificationEngine} from '../engine/chekEngine';
import {NeuromorphicSubstrate} from '../engine/neuromorphicSubstrate';

interface Props{chekEngine:ChekVerificationEngine;governorEngine:GovernorPolicyEngine;substrate:NeuromorphicSubstrate;currentProposal:ConvergedProposal|null;governorRecord:GovernorVaultRecord|null;twinMindCase:TwinMindCase|null;onVerified:(record:ChekVerificationRecord)=>void;}
export const ChekTerminalComponent:React.FC<Props>=({chekEngine,governorEngine,substrate,currentProposal,governorRecord,twinMindCase,onVerified})=>{
 const[stages,setStages]=useState<ChekAuditStage[]>([]),[invariants,setInvariants]=useState<InvariantEvaluation[]>([]),[latest,setLatest]=useState<ChekVerificationRecord|null>(null),[busy,setBusy]=useState(false),[tab,setTab]=useState<'pipeline'|'proofs'|'vault'>('pipeline'); const vault=chekEngine.getVaultHistory();
 const verify=async()=>{if(!currentProposal)return;setBusy(true);const cert=governorRecord?await governorEngine.verifyAuthorization(governorRecord):false;const r=await chekEngine.verifyGovernedChain({proposal:currentProposal,governorRecord,twinMindCase,governorCertificateValid:cert,protectedBoundaryPassed:substrate.verifyProtectedBoundary().passed});setStages(r.stages);setInvariants(r.invariants);setLatest(r.vaultRecord);setBusy(false);};
 return <div className="space-y-6">
  <div className="relative overflow-hidden rounded-xl border border-emerald-500/40 bg-gradient-to-r from-emerald-950/60 via-slate-900/80 to-slate-950 p-6 shadow-xl"><Lock className="absolute right-8 top-8 w-40 h-40 text-emerald-400 opacity-10"/><div className="relative z-10 max-w-3xl space-y-2"><span className="px-2.5 py-0.5 rounded-full text-xs font-mono font-bold bg-emerald-900/80 text-emerald-300 border border-emerald-700">STAGE 6: CHEK INDEPENDENT VERIFICATION</span><h2 className="text-2xl font-black text-white">"The Checker Is Also Checked."</h2><p className="text-sm text-slate-300">CHEK verifies Patty's evidence discipline, independently reproduces Governor policy, checks the exact Governor decision and certificate, confirms protected-system integrity, and writes an immutable audit result. CHEK reports VALID, INVALID, INCONSISTENT, or UNVERIFIABLE. It never grants execution authority.</p></div></div>
  <div className="bg-slate-900/80 border border-slate-800 rounded-xl p-5 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3"><div><div className="text-xs font-mono text-slate-400">ACTIVE GOVERNED CHAIN:</div><div className="font-mono font-bold text-white">{currentProposal?.title||'No proposal available'}</div><div className="text-[11px] font-mono text-slate-500 mt-1">Governor: {governorRecord?.outcome||'NO DECISION'} • Case: {twinMindCase?.id||'NO CASE'}</div></div><button onClick={verify} disabled={busy||!currentProposal} className="px-4 py-2 rounded-lg bg-emerald-600 hover:bg-emerald-500 disabled:opacity-40 text-slate-950 text-xs font-mono font-bold flex gap-2 items-center"><ShieldCheck className="w-4 h-4"/>{busy?'Verifying...':'Run Independent CHEK'}</button></div>
  <div className="flex flex-wrap gap-2 border-b border-slate-800 pb-2">{([['pipeline','4-Gate Verification'],['proofs',`Governance Proofs (${invariants.length})`],['vault',`CHEK Vault (${vault.length})`]] as const).map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`px-3 py-2 rounded text-xs font-mono font-bold ${tab===id?'bg-emerald-900/60 text-emerald-200 border border-emerald-600':'text-slate-400'}`}>{label}</button>)}</div>
  {tab==='pipeline'&&<div className="space-y-3"><div className="grid grid-cols-1 md:grid-cols-4 gap-3">{[['AUDITOR','Evidence + provenance'],['CHECKER','Independent rule recompute'],['GATEWAY','Cross-system conformance'],['VAULT','Immutable audit record']].map((x,i)=>{const s=stages[i];return <div key={x[0]} className={`p-3 rounded-xl border font-mono ${s?.status==='PASSED'?'border-emerald-600 bg-emerald-950/30':s?.status==='FAILED'?'border-red-600 bg-red-950/30':'border-slate-800 bg-slate-900/60'}`}><div className="flex justify-between text-xs font-bold">{x[0]}{s?.status==='PASSED'?<CheckCircle2 className="w-4 h-4 text-emerald-400"/>:s?.status==='FAILED'?<XCircle className="w-4 h-4 text-red-400"/>:null}</div><div className="text-[11px] text-slate-400">{x[1]}</div></div>})}</div>{stages.map((s,i)=><div key={i} className="p-4 bg-slate-950 border border-slate-800 rounded-lg font-mono text-xs"><div className="font-bold text-white">{s.title}</div>{s.details.map((d,j)=><div key={j} className="text-slate-300 mt-1">• {d}</div>)}</div>)}{!stages.length&&<div className="p-8 text-center border border-dashed border-slate-800 rounded-xl text-xs font-mono text-slate-400">Run CHEK to independently verify the governed chain.</div>}</div>}
  {tab==='proofs'&&<div className="space-y-3">{invariants.map(inv=><div key={inv.id} className={`p-4 bg-slate-950 rounded-lg border font-mono text-xs ${inv.passed?'border-emerald-700/60':'border-red-700/60'}`}><div className="flex justify-between"><span className="font-bold text-white">{inv.ruleCode} • {inv.name}</span><span className={inv.passed?'text-emerald-400':'text-red-400'}>{inv.passed?'VERIFIED':'FAILED'}</span></div><div className="text-slate-400 mt-2">{inv.formula} → <span className="text-cyan-300">{inv.computedValue}</span></div></div>)}</div>}
  {tab==='vault'&&<div className="bg-slate-900/80 border border-slate-800 rounded-xl p-5 space-y-3"><div className="flex gap-2 items-center text-sm font-mono font-bold text-white"><Database className="w-4 h-4 text-cyan-400"/>Independent CHEK Evidence Vault</div>{vault.map(r=><div key={r.index} className="p-3 bg-slate-950 border border-slate-800 rounded font-mono text-xs"><div className="flex justify-between"><span className="text-cyan-300">BLOCK #{r.index}</span><span className={r.outcome==='VALID'?'text-emerald-400':r.outcome==='INCONSISTENT'?'text-amber-400':'text-red-400'}>{r.outcome}</span></div><div className="text-slate-400 mt-1">{r.reason}</div></div>)}</div>}
  {latest&&<div className="p-4 bg-slate-950 border border-slate-800 rounded-xl flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3"><div><div className="text-xs font-mono text-slate-400">CHEK VERIFICATION RESULT</div><div className={`font-mono font-black ${latest.outcome==='VALID'?'text-emerald-400':'text-red-400'}`}>{latest.outcome}</div><div className="text-xs font-mono text-slate-400">{latest.reason}</div></div>{latest.outcome==='VALID'&&governorRecord?.outcome==='AUTHORIZED'?<button onClick={()=>onVerified(latest)} className="px-5 py-2.5 rounded-lg bg-gradient-to-r from-emerald-600 to-cyan-600 text-slate-950 font-mono text-xs font-black flex items-center gap-2">Continue with Governor Authorization <ArrowRight className="w-4 h-4"/></button>:<div className="px-4 py-2 rounded border border-red-800 bg-red-950/50 text-red-300 font-mono text-xs">NO VERIFIED AUTHORIZATION MAY CROSS THE OUTPUT BOUNDARY</div>}</div>}
 </div>;
};